create: ## force build skeleton laminas MVC
	composer create-project --ignore-platform-reqs -s dev laminas/laminas-mvc-skeleton ./laminas

install: ## force install laminas MVC
	composer install --ignore-platform-reqs